name: CI/CD with Approval

on:
  push:
    branches: [main]

jobs:
  # 自动执行测试和构建
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "build..."

  # 自动部署到预发布环境
  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy to staging
        run: echo "Deploying to staging..."

  # 需要人工审批后部署到生产环境
  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: test  # 关联配置的 Environment
    steps:
      - name: Deploy to production
        run: echo "Deploying to production..."
